name:                confcrypt
version:             0.1.0.0
github:              "githubuser/confcrypt"
license:             MIT
author:              "Chris Coffey"
maintainer:          "chris@collegevine.com"
copyright:           "2018 Chris Coffey, CollegeVine"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/confcrypt#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- text
- cryptonite
- mtl
- transformers
- attoparsec
- containers

library:
  source-dirs: src
  exposed-modules:
    - ConfCrypt.Types
  default-extensions: MultiParamTypeClasses OverloadedStrings FlexibleContexts FlexibleInstances NamedFieldPuns
        TupleSections


executables:
  confcrypt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - confcrypt

tests:
  confcrypt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - confcrypt
